### ISSUE TITLE
ARMv7 builds gone?

### ISSUE THREAD

**Issue by jjvdgeer** [etechonomy/joplin-server#11] opened 2024-01-08 21:32 UTC
It seems the armv7 builds are gone. Will they be back?

**Comment by etho201** [comment] 2024-02-02 06:05
The issue with the armv7 builds failing revolves around a memory (RAM) limit of 4GB due to armv7 being a 32-bit architecture. Something taking place in the yarn build command is causing builds for armv7 to spike past that memory limit and thus the build fails. I'm tracking a similar issue [here](https://github.com/yarnpkg/berry/issues/4916) and unfortunately it's still an open issue with no reasonable fix at this time.

**Comment by jjvdgeer** [comment] 2024-02-02 11:08
That's unfortunate :( Maybe it's time to get away from 32bit ARM but want to stay on ARM and I am using a QNAP and don't want to switch to another vendor. However they don't seem to have a model that has replaceable/expandable RAM and 64-bit ARM (yet?) :(

**Comment by neutmute** [comment] 2024-07-25 02:49
Is it possible to build for `aarch64`? (Raspberry Pi 4)

```
openhabian@openhab2:/opt/docker $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
openhabian@openhab2:/opt/docker $ uname -r
6.1.21-v8+
openhabian@openhab2:/opt/docker $ uname -m
aarch64
```

(Evernote tried to sting me for their doubled yearly subscription so time to migrate!)

**Comment by etho201** [comment] 2024-07-25 05:15
`arm64` is the same thing as `aarch64` -- You can run this just fine on your Raspberry Pi 4 with 64-bit OS you have installed.

**Comment by neutmute** [comment] 2024-07-28 00:26
Ah. I had this `docker-compose.yml` fragment
```
services:
  joplin2-server:
    image: etechonomy/joplin-server
...snip...

```

and this error

```openhabian@openhab2:/opt/docker/j2 $ docker-compose up -d
Creating network "j2_default" with the default driver
Pulling joplin2-server (etechonomy/joplin-server:)...
latest: Pulling from etechonomy/joplin-server
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries
```

Will test with 
```services:
  joplin2-server:
    image: etechonomy/joplin-server #:2.13.3  # Last armv7 version
    platform: linux/arm64```

and PR an update to the example docker-compose when confirmed working 👍

**Comment by neutmute** [comment] 2024-07-28 07:37
...nope. Doesn't seem to work. The container recycles with error 159. Repo below
Note the overridden `entrypoint` to try and isolate to the container. 

```services:
  joplin2-server:
    image: etechonomy/joplin-server #:2.13.3  # Last armv7 version
    container_name: joplin-server2
    platform: linux/arm64
    entrypoint: "tail -f /dev/null"
    environment:
        - APP_BASE_URL=https://192.168.20.5:5400
        - APP_PORT=5400
        - DB_CLIENT=pg
        - POSTGRES_PASSWORD=joplinWeeee!
        - POSTGRES_DATABASE=joplin2-db
        - POSTGRES_USER=joplin
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=joplin-db
    restart: unless-stopped
    ports:
      - 22301:22300
```

**Comment by etho201** [comment] 2024-08-05 03:55
@neutmute -- This is not an issue with the image. I'm also running it on an `aarch64` system and I do not have the issue. What version of docker and docker-compose do you have?

**Comment by neutmute** [comment] 2024-08-08 10:49
Good question. Here are the versions.

```
$ docker --version
Docker version 27.1.1, build 6312585

$ docker compose version
Docker Compose version v2.29.1

$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1w  11 Sep 2023
```

My launch script _was_ using the old `docker-compose` so I switched to `docker compose`. 
Without the platform directive, the error is now
` ! joplin-server The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested`

With the platform directive of `platform: linux/arm64`, then Joplin server starts but goes into a restart loop.

But...my version of Raspbian is a bit old...
```  
Release = Raspbian GNU/Linux 11 (bullseye)
Kernel = Linux 6.1.21-v8+
Platform = Raspberry Pi 4 Model B Rev 1.4
```

and has had a few things installed on it over time.

I plan to repave it with a fresh install this weekend.
Let me do that and get back to you.

**Comment by neutmute** [comment] 2024-08-11 03:32
It works now after a fresh install of latest Raspberry Pi OS 🥳🥳

```
openhab@openhab-pi:/opt/docker/joplin $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
openhab@openhab-pi:/opt/docker/joplin $ uname -r
6.6.31+rpt-rpi-v8
openhab@openhab-pi:/opt/docker/joplin $ uname -m
aarch64
```

```
Docker version 27.1.1, build 6312585
Docker Compose version v2.29.1
```

Interestingly, after I restored my docker and data files postgres was complaining about

`The database cluster was initialized without USE_FLOAT8_BYVAL but the server was compiled with USE_FLOAT8_BYVAL.`

Which from what I can tell, it was running a 32bit image? 
So random idea is that docker was in 32bit mode somehow on the old OS? 

Anyway, all fixed now, thanks very much for your responses and effort on this container 🤝

**Comment by etho201** [comment] 2024-08-19 04:34
I was scratching my head a bit as to why it wasn't working for you, but it makes sense that you were running Docker in 32-bit (x86) mode on the 64-bit (x86_64) OS. I guess you somehow had the x86 version of Docker installed? Anyway, thank you for reporting back on this and glad you got things working!

**Closed** 2024-08-19 04:34 UTC
